<?php  
/**
 * Implements hook_permission
 */

function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for demo module.'),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function demo_node_view($node, $view_mode, $langcode) {
	$node->content['demo_field'] = array(
		'#type' 	=> 'markup',
		'#markup'	=> '<p>'.t('This is only a demo.').'</p>',
		'#weight'	=> -10,
	);

	krumo($node);
}