<?php  
// Keep in mind to write a hook replace the word hook with our module name.
/**
 * Implements hook_permission
 */

function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for demo module.'),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function demo_node_view($node, $view_mode, $langcode) {
	$node->content['demo_field'] = array(
		'#type' 	=> 'markup',
		'#markup'	=> '<p>'.t('This is only a demo.').'</p>',
		'#weight'	=> -10,
	);

	krumo($node);
}

/**
 * Implements hook_menu
 */
function mymodule_menu(){
	$items['about'] = array(
		'title' 			=> 'About us',
		'description'		=> 'A description of us.',
		'page callback' 	=> 'mymodule_about',
		'access arguments'	=> array('access content'),
	);
	return $items;
}

/**
 * Implements form_hook
 */
function example_color_form() {
	$form['color'] = array(
		'#type'		=>	'select',
		'#title'	=>	t('Favourite colour'),
		'#options'	=>	drupal_map_assoc(array(
			t('red'),t('blue'),t('periwinkle'),
		)),
	);
	$form['submit']	= array(
		'#type'		=> 'submit',
		'#value'	=>	t('Submit'),
	);

	return $form;
}